name: CI Assignment 6

on:
  # push:
  #   branches:
  #     - '*'
  pull_request:
    types:
      - synchronize
      - opened
      - reopened
    # paths:
    # - 'packages/assignment-6/**'
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-dependencies
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Build Assignment 6
        run: pnpm -F assignment-6 run build
      - name: Comment PR on build failure
        if: ${{ failure() }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.TOKEN_FOR_CI }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '빌드 과정에서 오류가 발생했습니다. 로그를 확인해 주세요.'
            })

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js and Dependencies
        uses: ./.github/actions/setup-node-dependencies
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run linter
        run: pnpm -F assignment-6 run lint > lint_results.txt
        working-directory: packages/assignment-6
      - name: Comment PR with lint results
        if: always()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TOKEN_FOR_CI }}
          script: |
            const fs = require('fs');
            const lintResults = fs.readFileSync('packages/assignment-6/lint_results.txt', 'utf8');
            const comment = `## ESLint Results\n\n\`\`\`\n${lintResults}\n\`\`\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  test:
    runs-on: ubuntu-latest
    steps:
      - name: job3 구현
        run: echo "job3의 내용을 구현해주세요"

  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: job4 구현
        run: echo "job4의 내용을 구현해주세요"

  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: job5 구현
        run: echo "job5의 내용을 구현해주세요"
